theme: jekyll-theme-dinky
title: Caleb's Website
description: Welcome to my website! It is currently a work in progress but it will eventually be home to my collection of academic and creative pursuits. 
